baseurl = "https://mannarella.it"
languageCode = "it-It"
theme = "hello-friend-ng"
DefaultContentLanguage = "it"
rssLimit  = 30
paginate = "25"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Licenza Creative Commons" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a><br />Quest'opera è distribuita con Licenza <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribuzione - Non commerciale - Condividi allo stesso modo 4.0 Internazionale</a>.'
enableRobotsTXT = true
enableEmoji     = true

[author]
name = "Andrea Mannarella"

[params]
dateform        = "2 Jan 2006"
dateformShort   = "2 Jan"
dateformNum     = "02/01/2006"
dateformNumTime = "02/01/2006 15:04"
disableReadOtherPosts = false
justifyContent = true
contentTypeName = "posts"
defaultTheme = "dark"
   
[params.logo]
logoText     = "$ cd /home/"
logoHomeLink = "/"

[languages]
  [languages.en]
    title = "Did you try turning it off and on again?"
    homeSubtitle = "Talking about tecnology, random stuff..."
    languageName = "English"
    readOtherPosts = "Read other posts"
    weight = 0
	[languages.en.menu]
  	[[languages.en.menu.main]]
	    identifier = "whoami"
    	    name       = "About"
    	    url        = "about/"
            weight = -100
	[[languages.en.menu.main]]
	    identifier = "blog"
    	    name       = "Blog"
    	    url        = "/posts"
            weight = -50
    
  [languages.it]
    title = "Hai provato a spegnere e riaccendere?"
    homeSubtitle = "Parlo di tecnologia, cose a caso..."
    languageName = "Italiano"
    readOtherPosts = "Leggi altri articoli"
    weight    = -100
    [languages.it.menu]
  	[[languages.it.menu.main]]
	    identifier = "whoami"
    	    name       = "Chi sono"
    	    url        = "about/"
            weight = -100
	[[languages.it.menu.main]]
	    identifier = "blog"
    	    name       = "Blog"
    	    url        = "/posts"
            weight = -50

    
[[params.social]]
name = "github"
url  = "https://github.com/andrimanna"

[[params.social]]
name = "linkedin"
url  = "https://www.linkedin.com/in/mannarellandrea/"

[[params.social]]
name = "telegram"
url  = "https://telegram.me/andrimanna"

[[params.social]]
name = "youtube"
url  = "https://www.youtube.com/channel/UCOqjw1xz1k1Dc9I3S8xl4kg"

[[params.social]]
name = "email"
url  = "mailto:andrea@mannarella.it"

[[params.social]]
name = "twitter"
url  = "https://twitter.com/MannarellAndrea"
