baseurl = "https://mannarella.it"
languageCode = "it"
theme = "hello-friend-ng"
DefaultContentLanguage = "it"
rssLimit  = 10
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true

[author]
name = "Andrea Mannarella"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02/01/2006"
  dateformNumTime = "02/01/2006 15:04"
  disableReadOtherPosts = false
  justifyContent = true
  contentTypeName = "posts"
  defaultTheme = "dark"

[params.logo]
   logoText     = "$ cd /home/"
   logoHomeLink = "/"


[languages]
  [languages.en]
    title = "Did you try turning it off and on again?"
    readOtherPosts = "Read other posts"
    weight = 2
    
  [languages.it]
    title = "Hai provato a spegnere e riaccendere?"
    readOtherPosts = "Leggi altri post"
    weight    = 1
    
[menu]
  [[menu.main]]
    name       = "blog"
    url        = "/posts"
    
  [[menu.main]]
    identifier = "about"
    name       = "whoami"
    url        = "about/"

[[params.social]]
  name = "github"
  url  = "https://github.com/andrimanna"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/in/mannarellandrea/"

[[params.social]]
  name = "telegram"
  url  = "https://telegram.me/andrimanna"

[[params.social]]
  name = "youtube"
  url  = "https://www.youtube.com/channel/UCOqjw1xz1k1Dc9I3S8xl4kg"
