baseurl = "https://mannarella.gq"
languageCode = "it"
theme = "hello-friend-ng"
DefaultContentLanguage = "it"
rssLimit  = 10
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
title = "MannaWebSite"
keywords = "portfolio mannarella"

[author]
name = "Andrea Mannarella"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "02/01/2006"
  dateformNumTime = "02/01/2006 15:04 -0700"
  disableReadOtherPosts = false
  justifyContent = true
  contentTypeName = "posts"
  defaultTheme = "dark"

[params.logo]
   logoText     = "$ cd /home/"
   logoHomeLink = "/"


[languages]
  [languages.en]
    subtitle = "Andrea Mannarella's portfolio"
    readOtherPosts = "Read other posts"
    weight    = 2
    
  [languages.it]
    subtitle = "Portfolio di Andrea Mannarella"
    readOtherPosts = "Leggi altri post"
    weight    = 1
    
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/"

[[params.social]]
  name = "email"
  url  = "mailto:nobody@example.com"

[[params.social]]
  name = "github"
  url  = "https://github.com/"

[[params.social]]
  name = "linkedin"
  url  = "https://www.linkedin.com/"

[[params.social]]
  name = "stackoverflow"
  url  = "https://www.stackoverflow.com/"
